Repository githedgehog/fabricator, pull requests merged in 2025-07, with the labels that each got.

#724 ci(vlab-upgrade): test upgrades from 25.03
  .github/workflows/ci.yaml
Labels: skip-hlab

#723 bump(gw): dp and frr containers to more or less working versions
  pkg/fab/versions.go
Labels: skip-hlab

#722 fix(release-test): derive hhnet cmd for server-1
  pkg/hhfab/release.go
  pkg/hhfab/testing.go
Labels: release-test

#740 bump: dataplane to merged code with NAT and metrics
  pkg/fab/versions.go
Labels: skip-hlab

#750 feat: allow to setup alloy on gateway for frr/dp/unix
  go.mod
  go.sum
  pkg/fab/comp/alloy/alloy.go
  pkg/fab/comp/fabric/fabric.go
  pkg/fab/comp/gateway/gateway.go
  pkg/fab/versions.go
  vendor/go.githedgehog.com/gateway/api/gateway/v1alpha1/gateway_types.go
  vendor/go.githedgehog.com/gateway/api/gateway/v1alpha1/zz_generated.deepcopy.go
  vendor/go.githedgehog.com/gateway/api/meta/config.go
  vendor/modules.txt
Labels: skip-hlab

#769 Further refactor ci and reuse vlab workflow for hlab as well
  .github/workflows/ci.yaml
  .github/workflows/ghcr-cleanup.yaml
  .github/workflows/run-vlab.yaml
Labels: skip-hlab, skip-vlab

#770 ci: cleanup ci labels
  .github/workflows/ci.yaml
Labels: ci:-vlab, ci:+hlab

#771 ci: adjust ci after switching to reusable workflows
  .github/workflows/ci.yaml
  .github/workflows/run-vlab.yaml
  config/docker/hhfab-node-config/.gitignore
Labels: ci:-vlab

#777 ci: fix permissions
  .github/workflows/ci.yaml
Labels: ci:-vlab, ci:-upgrade

#799 bump: dp and frr to latest
  pkg/fab/versions.go
Labels: ci:-upgrade

#800 bump: complete kube bumps
  go.mod
  go.sum
  vendor/k8s.io/utils/buffer/ring_growing.go
  vendor/modules.txt
Labels: ci:-vlab

#775 release-test: add coverage for port breakouts
  pkg/hhfab/release.go
Labels: ci:-vlab, ci:-upgrade, ci:+release, ci:+hlab

#796 release-test: static external coverage + pause on fail fix
  pkg/hhfab/release.go
Labels: ci:+release, ci:+hlab

#814 ci: fix publishing release test results
  .github/workflows/ci.yaml
Labels: ci:-upgrade, ci:+release

#822 ci: increase oem size and include gw into onie tests
  .github/workflows/ci.yaml
  pkg/fab/recipe/build.go
Labels: ci:-upgrade
