Repository githedgehog/fabricator, pull requests merged in 2025-10, with the labels that each got.

#1012 bump: alloy => v1.11.0
  pkg/fab/README.md
  pkg/fab/versions.go
Labels: ci:+hlab

#1014 fix(ci): always publish release-test results
  .github/workflows/ci.yaml
Labels: ci:-upgrade, ci:+release

#1007 fix(test): add check for empty switch for RoCE test
  pkg/hhfab/release.go
Labels: ci:+release, ci:+hlab

#1020 fix(ci): fix vlab slug
  .github/workflows/run-vlab.yaml
Labels: ci:-upgrade
