Repository githedgehog/fabricator, pull requests merged in 2025-09, with the labels that each got.

#971 chore: more iperf3 error report tweaks
  pkg/hhfab/testing.go
Labels: ci:+release

#973 chore: add release-test list option
  cmd/hhfab/main.go
  pkg/hhfab/release.go
  pkg/hhfab/testing.go
Labels: ci:+release

#978 chore: publish bash comp package
  pkg/fab/README.md
Labels: ci:-vlab

#990 fix(release): always use single resulting port breakout
  pkg/hhfab/release.go
Labels: ci:-upgrade, ci:+release, ci:+hlab

#1002 bump: september flatcar
  pkg/fab/README.md
  pkg/fab/versions.go
Labels: ci:+hlab

#988 release-test: static-external stability
  pkg/hhfab/release.go
Labels: ci:-vlab
