Repository githedgehog/fabricator, pull requests merged in 2025-05, with the labels that each got.

#593 chore: bump flatcar to 4152.2.3
  pkg/fab/README.md
  pkg/fab/versions.go
Labels: release, skip-hlab

#598 bump: k3s to 1.32.4
  pkg/fab/README.md
  pkg/fab/versions.go
Labels: skip-hlab

#600 bump: k9s to v0.50.4
  pkg/fab/README.md
  pkg/fab/versions.go
Labels: skip-hlab

#601 chore: double fabricator-controller mem limits
  config/manager/manager.yaml
Labels: skip-hlab

#604 bump: k9s to v0.50.5
  pkg/fab/README.md
  pkg/fab/versions.go
Labels: skip-hlab

#605 feat(support): remove preview restriction
  cmd/hhfabctl/main.go
Labels: skip-hlab

#610 fix: remove second k3s upgrade attempt
  pkg/fab/recipe/control_upgrade.go
Labels: skip-hlab

#609 feat(recipe): manage k9s plugins and add tailing agent logs
  pkg/fab/comp/k9s/k9s.go
  pkg/fab/comp/k9s/k9s_plugins.yaml
  pkg/fab/recipe/control_butane.tmpl.yaml
  pkg/fab/recipe/control_install.go
  pkg/fab/recipe/control_upgrade.go
Labels: skip-hlab

#616 ci(vlab): test upgrades from 25.02
  .github/workflows/ci.yaml
Labels: skip-hlab

#629 fix: repeated initial setup in release test
  pkg/hhfab/release.go
Labels: release-test, skip-hlab

#644 test: dhcp custom lease time in release-test
  pkg/hhfab/release.go
Labels: release-test
