Repository githedgehog/fabricator, pull requests merged in 2025-06, with the labels that each got.

#647 ci: workaround to fix ntp desync
  .github/workflows/ci.yaml
Labels: release-test

#664 chore: ignore iperf speed for virtual switches
  pkg/hhfab/testing.go
Labels: release-test, skip-hlab

#686 fix(gw): update to latest image names and tags
  pkg/fab/comp/gateway/gateway.go
  pkg/fab/versions.go
Labels: skip-hlab

#688 bump(frr): use version with fixed frr-reload exec
  pkg/fab/versions.go
Labels: skip-hlab

#696 chore(gw): only vxlan traffic instead of all udp
  pkg/fab/recipe/node_install.go
Labels: skip-hlab

#695 ci: add govulncheck scan workflow
  .github/workflows/govulncheck_scan.yaml
Labels: skip-hlab, skip-vlab
